/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Button_Left.h"
#include "Button_Left_aliases.h"
#include "LED_Red_2.h"
#include "LED_Red_2_aliases.h"
#include "Clock_1.h"
#include "Button_Left_Int.h"
#include "LED_Red_1.h"
#include "LED_Red_1_aliases.h"
#include "Button_Right.h"
#include "Button_Right_aliases.h"
#include "Button_Right_Int.h"
#include "LED_Yellow_2.h"
#include "LED_Yellow_2_aliases.h"
#include "LED_Yellow_1.h"
#include "LED_Yellow_1_aliases.h"
#include "LED_Green_2.h"
#include "LED_Green_2_aliases.h"
#include "LED_Green_1.h"
#include "LED_Green_1_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

